import type { AppointmentRow } from "@/feature-module/components/pages/clinic-modules/patient-details";
import type { Patient } from "../types/typedefs";

export const mockPayments = [
  {
    id: "#TNX0025",
    description: "General Consultation",
    paidDate: "2025-04-30",
    method: "CASH",
    amount: 800,
    status: "COMPLETED",
  },
  {
    id: "#TNX0024",
    description: "Dental Cleaning",
    paidDate: "2025-04-15",
    method: "Debit Card",
    amount: 930,
    status: "PENDING",
  },
  {
    id: "#TNX0023",
    description: "Eye Checkup",
    paidDate: "2025-04-02",
    method: "Cheque",
    amount: 850,
    status: "COMPLETED",
  },
  {
    id: "#TNX0022",
    description: "X-Ray",
    paidDate: "2025-03-27",
    method: "Debit Card",
    amount: 80,
    status: "COMPLETED",
  },
  {
    id: "#TNX0021",
    description: "Physiotherapy Session",
    paidDate: "2025-03-12",
    method: "PayPal",
    amount: 650,
    status: "COMPLETED",
  },
  {
    id: "#TNX0020",
    description: "Cardiac Screening",
    paidDate: "2025-03-05",
    method: "Cheque",
    amount: 430,
    status: "COMPLETED",
  },
  {
    id: "#TNX0019",
    description: "Skin Allergy Test",
    paidDate: "2025-02-24",
    method: "Debit Card",
    amount: 300,
    status: "PENDING",
  },
  {
    id: "#TNX0018",
    description: "Blood Test",
    paidDate: "2025-02-16",
    method: "Cheque",
    amount: 450,
    status: "COMPLETED",
  },
  {
    id: "#TNX0017",
    description: "ENT Consultation",
    paidDate: "2025-02-01",
    method: "Debit Card",
    amount: 570,
    status: "COMPLETED",
  },
  {
    id: "#TNX0017-B",
    description: "Nutrition Counseling",
    paidDate: "2025-01-25",
    method: "PayPal",
    amount: 800,
    status: "COMPLETED",
  },
];

export const mockAppointments: AppointmentRow[] = [
  {
    id: "1",
    planId: "1",
    therapistId: "1",
    startsAt: "2025-04-30T09:30:00Z",
    endsAt: "2025-04-30T10:30:00Z",
    sessionType: "REGULAR",
    location: "CLINIC",
    status: "COMPLETED",
    noteEn: "Regular physiotherapy session completed successfully",
    noteAr: null,
    cancelReason: null,
    createdAt: "2025-04-25T10:00:00Z",
    updatedAt: "2025-04-30T10:30:00Z",
    therapist: {
      name: "Dr. Mick Thompson",
      specialty: "Physiotherapist",
      avatarSrc: "assets/img/doctors/doctor-01.jpg",
    },
    sessionTypeLabel: "Regular Session",
    locationLabel: "In-person",
    statusLabel: "Completed",
  },
  {
    id: "2",
    planId: "1",
    therapistId: "2",
    startsAt: "2025-04-15T11:20:00Z",
    endsAt: "2025-04-15T12:20:00Z",
    sessionType: "SHOCK_WAVE",
    location: "CLINIC",
    status: "CHECKED_IN",
    noteEn: "Shock wave therapy session in progress",
    noteAr: null,
    cancelReason: null,
    createdAt: "2025-04-10T14:00:00Z",
    updatedAt: "2025-04-15T11:20:00Z",
    therapist: {
      name: "Dr. Sarah Johnson",
      specialty: "Physical Therapist",
      avatarSrc: "assets/img/doctors/doctor-02.jpg",
    },
    sessionTypeLabel: "Shock Wave Therapy",
    locationLabel: "In-person",
    statusLabel: "Checked In",
  },
  {
    id: "3",
    planId: "1",
    therapistId: "3",
    startsAt: "2025-04-02T08:15:00Z",
    endsAt: "2025-04-02T09:15:00Z",
    sessionType: "HOME",
    location: "HOME",
    status: "CANCELLED",
    noteEn: null,
    noteAr: null,
    cancelReason: "PATIENT_REQUEST",
    createdAt: "2025-03-28T16:30:00Z",
    updatedAt: "2025-04-01T20:00:00Z",
    therapist: {
      name: "Dr. Emily Carter",
      specialty: "Home Care Specialist",
      avatarSrc: "assets/img/doctors/doctor-03.jpg",
    },
    sessionTypeLabel: "Home Session",
    locationLabel: "Home Visit",
    statusLabel: "Cancelled",
  },
];

export const patientData: Patient = {
  id: "PT0025",
  fullName: "Samir Haddad",
  dob: "1990-05-01",
  gender: "M",
  phone: "0790412554",
  hasInsurance: false,
  balance: "0.00",
  extraCare: true,
  nationalId: "A123456009",
  addressJson: {
    city: "Amman",
    street: "Wadi Saqra",
  },
  notes: "First visit",
  createdAt: "2025-08-19T07:34:23.644Z",
  updatedAt: "2025-08-19T07:37:02.610Z",
  plans: [
    {
      id: "1",
      patientId: "1",
      planType: "PACKAGE",
      packageCode: "PKG10_15",
      priceBasis: "PACKAGE_RATE",
      primaryTherapistId: "3",
      startDate: "2025-08-10",
      status: "ONGOING",
      totalSessions: 10,
      remainingSessions: 10,
      targetFreqPerWeek: 1,
      referringDoctorId: "1",
      insuranceReferralAuth: "REF-ALI-001",
      freqAdvisory2w: false,
      initialDxTextEn: "MRI shows mild meniscus tear",
      initialDxTextAr: "تصوير بالرنين يظهر تمزقًا طفيفًا",
      initialDxFileId: null,
      createdAt: "2025-08-14T09:28:00.151Z",
      updatedAt: "2025-08-14T09:28:00.151Z",
    },
  ],
};
