import { all_routes } from "../../../feature-module/routes/all_routes";

const routes = all_routes;

export const SidebarData = [
  {
    tittle: "Main Menu",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Dashboard",
        link: "index",
        submenu: false,
        showSubRoute: false,
        icon: "layout-dashboard",
        base: "dashboard",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Patients",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "user-heart",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Patients", link: routes.patients },
          { label: "Patient Details", link: routes.patientDetails },
          { label: "Create Patient", link: routes.createPatient },
        ],
      },
      {
        label: "Appointments",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "calendar-check",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Appointments", link: routes.appointments },
          { label: "New Appointment", link: routes.newAppointment },
          { label: "Calendar", link: routes.appointmentCalendar },
        ],
      },
    ],
  },
  {
    tittle: "Admin",
    icon: "settings",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Discount Management",
        link: routes.discountManagement,
        submenu: false,
        showSubRoute: false,
        icon: "discount",
        base: "DiscountManagement",
        materialicons: "percent",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Audit Logs",
        link: routes.auditLogs,
        submenu: false,
        showSubRoute: false,
        icon: "file-text",
        base: "AuditLogs",
        materialicons: "history",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Development",
    icon: "code",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Error Display Examples",
        link: routes.errorDisplayExamples,
        submenu: false,
        showSubRoute: false,
        icon: "alert-triangle",
        base: "ErrorDisplayExamples",
        materialicons: "bug_report",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Error Test Suite",
        link: routes.errorDisplayTestSuite,
        submenu: false,
        showSubRoute: false,
        icon: "test-pipe",
        base: "ErrorDisplayTestSuite",
        materialicons: "science",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Reception Dashboard",
        link: routes.receptionDashboard,
        submenu: false,
        showSubRoute: false,
        icon: "dashboard",
        base: "ReceptionDashboard",
        materialicons: "dashboard",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "UI Components",
    icon: "layout",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Basic Components",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "box",
        base: "BasicComponents",
        materialicons: "widgets",
        dot: true,
        submenuItems: [
          { label: "Accordion", link: routes.uiAccordion },
          { label: "Alerts", link: routes.uiAlerts },
          { label: "Avatar", link: routes.uiAvatar },
          { label: "Badges", link: routes.uiBadges },
          { label: "Breadcrumb", link: routes.uiBreadcrumb },
          { label: "Buttons", link: routes.uiButtons },
          { label: "Button Groups", link: routes.uiButtonsGroup },
          { label: "Cards", link: routes.uiCards },
          { label: "Carousel", link: routes.uiCarousel },
          { label: "Collapse", link: routes.uiCollapse },
          { label: "Dropdowns", link: routes.uiDropdowns },
          { label: "Grid", link: routes.uiGrid },
          { label: "Images", link: routes.uiImages },
          { label: "Links", link: routes.uiLinks },
          { label: "List Group", link: routes.uiListGroup },
          { label: "Modals", link: routes.uiModals },
          { label: "Offcanvas", link: routes.uiOffcanvas },
          { label: "Pagination", link: routes.uiPagination },
          { label: "Placeholders", link: routes.uiPlaceholders },
          { label: "Popovers", link: routes.uiPopovers },
          { label: "Progress", link: routes.uiProgress },
          { label: "Scrollspy", link: routes.uiScrollspy },
          { label: "Spinner", link: routes.uiSpinner },
          { label: "Nav Tabs", link: routes.uiNavTabs },
          { label: "Toasts", link: routes.uiToasts },
          { label: "Tooltips", link: routes.uiTooltips },
          { label: "Typography", link: routes.uiTypography },
          { label: "Utilities", link: routes.uiUtilities },
        ],
      },
      {
        label: "Extended Components",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "layers",
        base: "ExtendedComponents",
        materialicons: "extension",
        dot: true,
        submenuItems: [
          { label: "Dragula", link: routes.dragula },
          { label: "Clipboard", link: routes.uiClipboard },
          { label: "Range Slider", link: routes.uiRangeslider },
          { label: "Lightbox", link: routes.uiLightbox },
          { label: "Rating", link: routes.uiRating },
          { label: "Counter", link: routes.uiCounter },
          { label: "Scrollbar", link: routes.uiScrollbar },
        ],
      },
    ],
  },
  {
    tittle: "Charts & Maps",
    icon: "bar-chart",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Charts",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "trending-up",
        base: "Charts",
        materialicons: "show_chart",
        dot: true,
        submenuItems: [
          { label: "Apex Charts", link: routes.chartApex },
          { label: "Chart.js", link: routes.chartJs },
        ],
      },
      {
        label: "Maps",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "map",
        base: "Maps",
        materialicons: "map",
        dot: true,
        submenuItems: [
          { label: "Leaflet Maps", link: routes.mapsLeaflet },
        ],
      },
    ],
  },
  {
    tittle: "Tables",
    icon: "table",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Basic Tables",
        link: routes.tablesBasic,
        submenu: false,
        showSubRoute: false,
        icon: "table",
        base: "TablesBasic",
        materialicons: "table_chart",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Data Tables",
        link: routes.dataTables,
        submenu: false,
        showSubRoute: false,
        icon: "database",
        base: "DataTables",
        materialicons: "storage",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Icons",
    icon: "star",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Icon Libraries",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "icons",
        base: "IconLibraries",
        materialicons: "palette",
        dot: true,
        submenuItems: [
          { label: "Font Awesome", link: routes.iconFontawesome },
          { label: "Tabler Icons", link: routes.iconTabler },
          { label: "Bootstrap Icons", link: routes.iconBootstrap },
          { label: "Remix Icons", link: routes.iconRemix },
          { label: "Ionic Icons", link: routes.iconIonic },
          { label: "Material Icons", link: routes.iconMaterial },
          { label: "Pe7 Icons", link: routes.iconPe7 },
          { label: "Themify Icons", link: routes.iconThemify },
          { label: "Weather Icons", link: routes.iconWeather },
          { label: "Typicon Icons", link: routes.iconTypicon },
          { label: "Flag Icons", link: routes.iconFlag },
        ],
      },
    ],
  },
  {
    tittle: "Forms",
    icon: "edit",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Form Components",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "file-text",
        base: "FormComponents",
        materialicons: "dynamic_form",
        dot: true,
        submenuItems: [
          { label: "Basic Inputs", link: routes.formBasicInputs },
          { label: "Checkbox & Radios", link: routes.formCheckboxRadios },
          { label: "Input Groups", link: routes.formInputGroups },
          { label: "Grid & Gutters", link: routes.formGridGutters },
          { label: "File Upload", link: routes.formFileupload },
          { label: "Horizontal Form", link: routes.formHorizontal },
          { label: "Vertical Form", link: routes.formVertical },
          { label: "Floating Labels", link: routes.formFloatingLabels },
          { label: "Form Validation", link: routes.formValidation },
          { label: "Select2", link: routes.formSelect2 },
          { label: "Form Pickers", link: routes.formPickers },
          { label: "Form Wizard", link: routes.formWizard },
          { label: "Form Mask", link: routes.formMask },
        ],
      },
    ],
  },
];
